services:
    ds-agent:
        image: ds-agent:0.1.0
        environment:
            DS_AGENT_PORT=3128
            DS_AGENT_REGISTRY_USERNAME=testuser
            DS_AGENT_REGISTRY_PASSWORD=test123
            DS_AGENT_SECRET=pwd123
        ports:
            - 3128:3128
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
